In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

print("All libraries loaded successfully ")

All libraries loaded successfully

In [3]:
import pandas as pd

url = "https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv"
df = pd.read_csv(url)

df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X = df.drop('medv', axis=1)
y = df['medv']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

print("Model trained")

Model trained

In [5]:
y_pred = model.predict(X_test)

print("Predictions:", y_pred[:5])
print("Actual:", y_test.values[:5])

Predictions: [28.99672362 36.02556534 14.81694405 25.03197915 18.76987992]
Actual: [23.6 32.4 13.6 22.8 16.1]

In [6]:
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MSE:", mse)
print("R2 Score:", r2)

MSE: 24.291119474973538
R2 Score: 0.6687594935356317

In [7]:
import pandas as pd

coefficients = pd.DataFrame(model.coef_, X.columns, columns=['Coefficient'])
coefficients.sort_values(by='Coefficient', ascending=False)

         Coefficient
rm          4.438835
chas        2.784438
rad         0.262430
indus       0.040381
zn          0.030110
b           0.012351
age        -0.006296
tax        -0.010647
crim       -0.113056
lstat      -0.508571
ptratio    -0.915456
dis        -1.447865
nox       -17.202633

In [8]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score

model2 = DecisionTreeRegressor(random_state=42)
model2.fit(X_train, y_train)

y_pred2 = model2.predict(X_test)

print("Decision Tree R2:", r2_score(y_test, y_pred2))

Decision Tree R2: 0.7570616506127126

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# split first
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# scale AFTER split
scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)

# train
model = LinearRegression()
model.fit(X_train_s, y_train)

# predict
y_pred = model.predict(X_test_s)

print("Correct Scaled R2:", r2_score(y_test, y_pred))

Correct Scaled R2: 0.668759493535632

In [10]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

# create model
rf = RandomForestRegressor(random_state=42)

# train
rf.fit(X_train, y_train)

# predict
y_pred_rf = rf.predict(X_test)

# evaluate
print("Random Forest R2:", r2_score(y_test, y_pred_rf))

Random Forest R2: 0.8925431501835708

In [11]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(rf, X, y, cv=5)

print("Cross-validation scores:", scores)
print("Average CV score:", scores.mean())

Cross-validation scores: [0.76853322 0.85529227 0.74597955 0.46997996 0.2651775 ]
Average CV score: 0.6209925006759389

In [13]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=5, shuffle=True, random_state=42)

scores = cross_val_score(rf, X, y, cv=kf)

print("Shuffled CV Scores:", scores)
print("Average:", scores.mean())

Shuffled CV Scores: [0.86281817 0.8460517  0.79460209 0.90545308 0.85587658]
Average: 0.8529603222344744

In [14]:
import pickle

# save model
with open("model.pkl", "wb") as f:
    pickle.dump(rf, f)

print("Model saved!")

Model saved!